### ISSUE TITLE
Prevent page breaks at less than ideal places.

### ISSUE THREAD

**Issue by DeanHickerson** [DeanHickerson/md-html-pdf#2]
Might be able to add some CSS to prevent page breaks at parts of the document which would be less than ideal.

```css
h1,h2,h3,h4,h5 {
  page-break-after: avoid;
}
```
